### ISSUE TITLE
Clarification of length usage

### ISSUE THREAD

**Issue by zam6ak** [isaacs/node-lru-cache#103]
Could someone clarify 

- how is the length in options being used by this library and
- a few examples on how to set it correctly

For example, in the docs (under usage) I see 
`length: function (n, key) { return n * 2 + key.length }`

Does this mean the key length should be added every time?
What if I am storing array of complex JS objects using a string key? 
Should I calculate length as array length plus key length? Or do I need to consider the object size as well?

A few examples would be really helpful.

Thanks
Z

**Comment by joeyhub** [comment]
The way it'll normally work is that if I do this: new LRU({max: 10}) then it will only store 10 items. If someone adds an eleventh item then an item will be removed.

The most common reason to use an LRU cache is to limit memory memory use. For example, you only have 1GB of RAM and don't want to use more than 100MB for caching.

If you want to cache objects that are reasonably uniform in size, for example, 1MB plus or minus 10% then you can reliably say store a max of 100 items and the memory usage should stay max out at 100MB plus or minus 10MB.

If all your items however have all kinds of sizes then it's not reliable to set the max size as the number of items stored.

Imagine for example if the objects were the names of every person in a given country with the country as a key.

Some countries only have a thousand people, some have a billion. A single item could be 1KB or 1GB times the lengths of the names which might also varies. Some countries might also have short names, some might have long names.

In real life the variations in sizes often aren't that extreme but you can still get things that are ten times or a hundred times bigger which is enough to mean either you waste memory because you have to set it according to the worst case (setting max to the total amount of memory you want to use divided by the memory of the biggest possible items) or risk using too much memory.

If you have a variation of +-10% then you would set a safety margin of around 9.1MB (100 - 100 / 1.1) so if you have 100MB available for cache you'd set it to 90.9MB to give a safety margin. That means you might waste 10MB which might be tolerable for many. If the error margin is 90%

To use the length function properly you really need an intent, to only use a certain amount of memory with a reasonable margin of error.

There are two approaches to this. The most common will be someone has something like this:

```
lru.set(1, [1, 2, 3, 4]);
lru.set(2, [1]);
```

While the arrays between keys 1 and 2 are different sizes, the items within them are the same size.

Having `length: item => item.length` would effectively give you the real number of items, instead of 2, it would give you 5. This approach simply corrects the count of items when the number of items varies per entry.

Any approach taken should at the least attempt to better represent the difference in size between items. By default it's assumed they're all the same size. Some people then calculate or fill the LRU to see the memory needed.

The other approach for more complicated cases is to give a length that's a closer approximation of real memory usage. For strings this is simple, as it's just length. For complex structured data it's more complex.

In any case for a few reasons people tend not to calculate exact memory usage for complex objects such as that it's expensive and the engine doesn't export means of doing this.

There are however libraries such as sizeof that can be used for the length function to bring it reasonable close to memory. Another simple approach is to use JSON.stringify([key, value]).length.

Either method has a margin of error and is an approximation but is often close enough unless you have really really tight memory restrictions.

Whether you should include some count or size calculation of the key, value or both really depends on a few things...

If you want to make it map to real memory use as close as is reasonably possible then you might want to measure the size of everything.

Otherwise if you just want to get something close to real relative size (such as the real number of items) rather than absolute size then you would focus on what changes in size the most. If the keys are all exactly 16 character long hashes then it doesn't make sense to waste time including their length.

You start by including the lengths of whatever varies in length the most. In some cases, you just have to work out what to do. If each entry is an array of strings, you might want to consider what varies in length more, the arrays or the strings. For example if the arrays are all of length 9 to 11 but all contain strings ranging from length 1 to 19 then you would return the some of the string lengths. If the strings are all 9 to 11 but the arrays 1 to 19 then you would use the array length.

You basically need to do the maths as well as testing to see how much memory is used yourself in each case.
