### ISSUE TITLE
What is the mean about option: max? what is the unit? byte? or kb?

### ISSUE THREAD

**Issue by moheqionglin** [isaacs/node-lru-cache#108]
I try below code:
```
var options = { max: 100,
    length: function (n, key) {console.log(`-${n} ${key}-`); return n + key.length;},
    dispose: function (key, n) { console.log(`delete ${key}`);},
    maxAge: 1000 * 60 * 60
    
}
var cache = LRU(options);
const repl = require('repl');

const replServer = repl.start({prompt: '> '});
for(var i = 0 ; i < 100000; i++){
    cache.set('k' + i, 'v' + i);
}
```
I had set max = 100, and length function And put  100000 item into cache. But it i can get every item, Why?  the max does not work?

**Comment by silverDrops** [comment]
max The maximum size of the cache, checked by applying the length function to all values in the cache. Not setting this is kind of silly, since that's the whole purpose of this lib, but it defaults to Infinity.

length Function that is used to calculate the length of stored items. If you're storing strings or buffers, then you probably want to do something like function(n, key){return n.length}. The default is function(){return 1}, which is fine if you want to store max like-sized things. The item is passed as the first argument, and the key is passed as the second argumnet.

**Comment by isaacs** [comment]
The unit is whatever you want it to be. It's just a number.

In v7, note that `max` is _always_ the "number of items", and `maxSize` is the calculated `size` values that you can customize if you like.
