### ISSUE TITLE
Length property doesn't work for number 

### ISSUE THREAD

**Issue by bhaveshj21** [isaacs/node-lru-cache#117]
var LRU = require("lru-cache")
  , options = { max: 2
              , length: function (n, key) { return n * 2 + key.length }
              , dispose: function (key, n) { n.close() }
              , maxAge: 1000 * 60 * 60 }
  , cache = LRU(options)
  console.log(cache.length)
  cache.set(1,10) // differentiate the key and the value
  cache.set(2,20)
  cache.set(3,30)
  console.log(cache.length)
  console.log(cache.get(1))
  console.log(cache.get(2))
  console.log(cache.get(3))
  console.log(cache)

In this case The length function is called every time you set a value in the cache. When you call cache.set(1,10), the function length you defined earlier has as parameters: n (the number 1) and key (the number 10).

So you see here that key.length is undefined because a number doesn't have a length property and a sum with undefined will be NaN.

**Comment by prashanthr** [comment]
By design of this library, the default length function returns 1.

The API allows for you to override the length function to supply your own with the following signature `(n, key) => { /* run custom logic */ }`. 

If you know you will be supplying numbers as keys, you certainly cannot call a length function on a number. You may as well rewrite your length function like this
```
...
length: function (n, key) { 
  let keyType = typeof key
  let length = 1
  switch (keyType) {
     case 'object':
        length = Object.keys(key).length
        break 
     case 'string':
        length = key.length
        break
     case 'number': 
        break
  }
  return n * 2 + length
}
...
```
