### ISSUE TITLE
Class constructor LRUCache cannot be invoked without 'new'

### ISSUE THREAD

**Issue by pubmikeb** [isaacs/node-lru-cache#147]
I upgraded **_LRUCache_** from **_4.1.5_** to **_5.1.1_**:

![27_000214](https://user-images.githubusercontent.com/17231333/51793859-a6abdb80-21c7-11e9-8b3d-95e5d78bdb25.png)

And after this upgrade I can't use `npm` anymore, any action causes the following error:

> «Class constructor LRUCache cannot be invoked without 'new'»

![27_000612](https://user-images.githubusercontent.com/17231333/51793891-f5f20c00-21c7-11e9-91d6-ab3e37c0794d.png)

Debug logs:
[2019-01-26T23_05_04_268Z-debug.log](https://github.com/isaacs/node-lru-cache/files/2799586/2019-01-26T23_05_04_268Z-debug.log)

The only way to solve the issue is completely reinstall Node.js.

**Comment by isaacs** [comment]
What you're doing is updating dependencies within the npm project itself.

I think that's not the right thing to be doing, since as you're finding, the npm project is not prepared to handle the breaking changes in lru-cache.

The best way to update npm is `npm install npm -g`, or update the version of node you're using.  You might be able to get more info (especially if I'm missing some Windows particulars) asking on https://npm.community/

**Comment by pubmikeb** [comment]
Thanks for the tips, but that's the point, I'm already using the latest stable version of both — **_npm_** and **_Node.js_**. I performed the update operation for multiple modules and only with **_lru-cache_** there is a problem, that's why I thought it might be useful to file the ticket.

**Comment by isaacs** [comment]
So... I'm confused, maybe?  What are you trying to accomplish?

If it's to tell me that there was a breaking change between v4 and v5 of this module, yeah, that's why the major version number changed.  npm hasn't updated to use v5.

**Comment by tvChan** [comment]
> So... I'm confused, maybe? What are you trying to accomplish?
> 
> If it's to tell me that there was a breaking change between v4 and v5 of this module, yeah, that's why the major version number changed. npm hasn't updated to use v5.

My node's version is 10.10.0 and npm's version is 6.7.0.
And if I use the LRUCache's version in 5.1.1 will appear the same error!
But if I user the LRUCache's version in 4.1.5,  the error doesn't appear anymore!

**Comment by isaacs** [comment]
This is going in weird directions.

If you have a problem with this module, please post a new issue with steps to reproduce it.

It is expected that the `new` keyword is required as of version 5.  That is by design.  That was the breaking change with the v5 major version increase.  Please update your code, or don't update your module.
