### ISSUE TITLE
Add 'disposed' callback option

### ISSUE THREAD

**Issue by domarmstrong** [isaacs/node-lru-cache#161]
Hey, I've used LRU cache for a few projects now, thanks for the work 😄.

I've run in to one thing at the moment; I want to know when a value has been disposed rather than before it will be disposed. I have a small abstraction around LRU cache which makes it subscribable so you can listen to keys being set, disposed, reset. But the consumers read the current value from the cache when they receive update events. When you read after a dispose event you will get the old value, where I need to get the new undefined value.

The 2 work arounds I found were:

1. Make my dispose event async, which isn't ideal and brings its own consistency issues.
2. Use another map which you read/update and keep in sync with LRU and use LRU for its dispose behaviour, this works but adds complexity.

The addition of another 'disposed' callback would give that little more flexibility. It would also allow people to immediately add the value back in to the cache as mentioned in the documentation:

> It's called before actually removing the item from the internal cache, so if you want to immediately put it back in, you'll have to do that in a nextTick or setTimeout callback or it won't do anything

```
const del = (self, node) => {
  if (node) {
    const hit = node.value
    if (self[DISPOSE])
      self[DISPOSE](hit.key, hit.value)

    self[LENGTH] -= hit.length
    self[CACHE].delete(hit.key)
    self[LRU_LIST].removeNode(node)

    if (self[DISPOSED])
      self[DISPOSED](hit.key, hit.value)
  }
}
```

**Comment by domarmstrong** [comment]
I'm happy to create a PR for this if its something you are OK with adding.

**Comment by ramzes13** [comment]
Any update here?

**Comment by isaacs** [comment]
So the issue is that you want to have an async dispose method that will wait until it's done disposing before continuing?

Wouldn't that make `cache.set()` have to be asynchronous?

Or do you just want to defer the `dispose()` call until after it's been removed from the cache, rather than before?

**Comment by isaacs** [comment]
A really simple way to maybe get what you want?

```js
cache = new LRU({ max, etc,
  dispose: (v, k, reason) => process.nextTick(() => {
    // now it's actually gone, and the cache is in a clean state
    doStuff(v, k, reason)
  },
})
```

**Comment by domarmstrong** [comment]
I'm using the cache in the browser and don't have `nextTick`, and using `setTimeout` is too late. Ideally it would be another sync callback `disposed` that runs immediately after deletion.

**Comment by isaacs** [comment]
@domarmstrong A pretty close parallel to `nextTick` would be `Promise.resolve().then(() => ...)`.  But yeah, it's still not "right away at the end of the current run-to-completion", but rather "some time before the next event loop pass (probably)".

I tried a quick sketch of adding a `disposedAfter()` method, but the problem there is that it's still not safe to re-add if the disposal happens during eviction, due to the way that `evict()` is optimized.

Here's the evict method:

```js
  evict () {
    const head = this.head
    const k = this.keyList[head]
    const v = this.valList[head]
    this.dispose(v, k, 'evict')
    this.removeItemSize(head)
    this.head = this.next[head]
    this.keyMap.delete(k)
    this.size --
    // <-- imagine if we did this.disposeAfter(v, k, 'evict') right here
    return head
  }
```

So it gets the current `head` of the list, pops it off, and then returns the `head` as the next index to be used.

```js
  newIndex () {
    if (this.size === 0) {
      return this.tail
    }
    if (this.size === this.max) {
      return this.evict()  // <-- this right here
    }
    if (this.free.length !== 0) {
      return this.free.pop()
    }
    // initial fill, just keep writing down the list
    return this.tail + 1
  }
```

```js
  set (k, v, {
    ttl = this.ttl,
    noDisposeOnSet = this.noDisposeOnSet,
    size = 0,
    sizeCalculation = this.sizeCalculation,
  } = {}) {
    let index = this.size === 0 ? undefined : this.keyMap.get(k)
    if (index === undefined) {
      // addition
      index = this.newIndex() // <-- getting the new index here from evict()
```

It's set up this way both for legibility in the codebase, as well as making it extremely performant, so we don't have to do a full deletion and keyMap index lookup if we already know the linked list address index that's being evicted.

So, what ends up happening if you do something like:

```js
const c = new LRU({ ..., disposeAfter: (v, k) => {
  if (someCondition) {
    c.set(k, v)
  }
}})
```

is that we stick a new thing in the cache, changing the ordering of the recency list and possibly even evicting another item, and _then_ return the index that we should have used prior to the `disposeAfter` method being called, so the next/previous links get all fubar, or you even can get two items thinking they have the same `index` value, which is really not ok.

I'm not sure how to provide a way to say "disposal has happened, _and_ the set() that triggered it is fully completed and done with the index" in a way that doesn't significantly impact performance.  At minimum, we'd have to tell `evict()` that this is part of a `set()`, which means a new boolean being passed to `newIndex()`, and checked on every eviction, and that is the hottest code path in this module.  Then I guess the old `head` value will have to get pushed onto the `this.free` stack, only to be immediately popped off.

So we will have replaced `return head` with 3 int writes (2 for the push(), one for the pop()) and added 2 function calls.

**Comment by isaacs** [comment]
Thinking this a little more, another way _might_ be to have a `disposed` list, and any time we dispose something, we add it to that list.  Then, once the eviction/setting/etc. is completely done, we call `this.disposeAfter` on all the items in that list, and clear the list.

But, that might still get screwey if you do something in `disposeAfter` that causes it to need to dispose another thing.

```
c = new LRU({
  max: 4,
  disposeAfter: (v, k) => {
    if (k === 2 || k === 3 || k === 4) {
      c.set(k, v)
    }
  }
})
c.set(4, 4)
c.set(3, 3)
c.set(2, 2)
c.set(1, 1)
c.set(0, 0)
// last set triggers eviction of 4, which is re-added when processing the disposed list
// but now while processing, adding 4 triggers eviction of 3 to the disposed list
// re-adding 3 triggers eviction of 2, which is added to disposed list and so on
```

So these things would have to be really carefully managed, or you'll end up either missing some or processing them out of order.

Patch welcome, I guess, assuming it comes with a mountain of tests and doesn't negatively impact performance.

**Comment by domarmstrong** [comment]
Thanks for the details. I'll try and put some time aside to have a go at it.

**Comment by isaacs** [comment]
Added `disposeAfter` on 7.3.0.  Turned out to not be such a bad perf impact.  And the order can be handled by always pushing into the array and then shifting out of it until the length is 0.  So, for example, this will stack overflow:

```js
const c = new LRU({
  max: 5,
  disposeAfter: (v, k, reason) => {
    console.error('DA', k, v)
    c.set(k, v + 1, { noDisposeOnSet: true })
  },
})
c.set(0, 0)
c.set(1, 1)
c.set(2, 2)
c.set(3, 3)
c.set(4, 4)
c.set(5, 5)
```

```
      this.disposed.push([v, k, 'evict'])
                    ^

RangeError: Maximum call stack size exceeded
    at Array.push (<anonymous>)
    at LRUCache.evict (/Users/isaacs/dev/isaacs/lru-cache/index.js:428:21)
    at LRUCache.newIndex (/Users/isaacs/dev/isaacs/lru-cache/index.js:405:19)
    at LRUCache.set (/Users/isaacs/dev/isaacs/lru-cache/index.js:363:20)
    at LRUCache.disposeAfter (/Users/isaacs/dev/isaacs/lru-cache/dispose-forever.js:5:7)
    at LRUCache.set (/Users/isaacs/dev/isaacs/lru-cache/index.js:394:14)
    at LRUCache.disposeAfter (/Users/isaacs/dev/isaacs/lru-cache/dispose-forever.js:5:7)
    at LRUCache.set (/Users/isaacs/dev/isaacs/lru-cache/index.js:394:14)
```
