### ISSUE TITLE
infinite loop while doing `forEach` + `delete`

### ISSUE THREAD

**Issue by yosiat** [isaacs/node-lru-cache#212]
Hi,

I am working on upgrading from v6 to v7, we have a case in our cache-wrapper that we need to support removing keys by regex..
we did that by doing `forEach` and calling `del`.

In v7 I noticed that I get infinite loop on `forEeach` and it's get called with `null` key & value, while in v6 it worked.

```javascript
const LRUCache = require('lru-cache');

const cache = new LRUCache({ max: 10 });

cache.set('a', {});
cache.set('b', {});

let iterCount = 0;
cache.forEach(function (value, key) {
  if (key == 'a') {
    cache.delete(key);
  }
  iterCount++;
});
console.log('iterCount', iterCount);
```

Running this on:
* node v14.19.0
* M1 Mac
* lru-cache version v7.4.2

Running the same script (and changing `delete` with `del`) with lru-cache 6.0.0 it finishes instantly.

My question is: is that a regression? is this working-as-designed in v7 where you can't delete & iterate the cache at the same time?

**Comment by isaacs** [comment]
Yeah, in v7 it iterates by walking the linked list to save creating a big array up front, so if you're changing the list order, it gets upset. I recently fixed this with purgeStale, you can create an array of items to delete and remove them all at the end. But it needs a better solution, it's definitely a foot gun.

**Comment by isaacs** [comment]
Hm, well, this is really a lot trickier to support than it seems.

What's happening is that you're plucking the key out of the linked list, and so if the item being removed is the last item in the list, it is no longer a match to `this.head` (which would break out of the loop) but also the previous pointer from that index goes nowhere (because it's just garbage data, there's nothing there).  

I kind of like the fact that you can iterate over things, adding to the list, and it'll iterate over the things added during the iteration.  But, that means that if you delete things, then there'll always be cases where you put the linked list into a state where it never exits, by modifying the list such that the current pointer index is no longer part of the list.

There are a few ways to handle the footgun, I think:

1. Get the list of keys/values up front when iterating, in an array, and iterate over that instead.  Slower, more memory used (especially if the iteration is not completed to the end), and mutations to the list will not be reflected.  But you can delete during the walk, and it'll always terminate.
2. Do not allow deletions during iteration.  This would force you to cache all the items you were intending to delete, but it's also quite annoying.
3. Check for the item matching `this.head` _before_ yielding it, and break out of the list if it was the last item at the time it was checked.  This can still loop forever if you do something like `for (const k of c.keys()) c.get(k)` because now every time we check `this.prev[index]`, it's been moved to the tail, so it just cycles on the last two items forever, even without deleting anything.
4. Get the previous item in the list prior to yielding it, and also make that the next step in the iteration, regardless of how the list might change in the meantime.  Of course, if you do `for (const k of c.keys()) c.delete(k - 1)` then that can still be a problem.
5. Always check that the item is a valid index by ensuring that `index === this.keyMap.get(this.keyList[index])`.  Still not sure what to do if it _has_ been deleted, though.  Break out of the interation?  Skip to the next item?  It feels like `for (const k of c.keys()) c.delete(k)` should Just Work to clear the cache.
6. Document that it's not safe to mutate the cache while iterating, and that you should do `for (const key of [...cache.keys()])` if that's your intention.

This feels like maybe a decent compromise between speed and safety:

```js
  *indexes ({ allowStale = this.allowStale } = {}) {
    if (this.size) {
      const { free } = this
      for (let i = this.tail, j; true; ) {
        j = i === this.head
        if (allowStale || !this.isStale(i)) {
          yield i
        }
        // either head now, or was head and head was deleted
        if (i === this.head || j && this.keyMap.get(this.keyList[i]) !== i) {
          break
        } else {
          i = this.prev[i]
        }
      }
    }
  }
```

(And the corresponding reverse for `*rindexes` of course.)

So if you delete the item, that's fine, it'll still walk next to its former "prev" member.  But if it was the head, and is no longer a valid index, then the walk is over.

**Comment by yosiat** [comment]
@isaacs thanks for the fix!

I decided to filter on `keys` and then do deletes, to avoid issues of iteration+deletion at the same time.
