### ISSUE TITLE
Provide a different fetchMethod for each call to fetch

### ISSUE THREAD

**Issue by hnafar** [isaacs/node-lru-cache#228]
Currently it seems the fetchMethod is provided when initializing the cache, this does not allow for
the type of usage originally described here: https://github.com/isaacs/node-lru-cache/issues/102

How would I go about providing different factory methods on each call to fetch?

e.g.

```javascript

getDbData: (id) => {
  const key - `from-db-${id}`;
  const value = cache.getOrCreate(key, () => db.getById(id));
  return value;
}

getAPIData: (id) => {
  const key - `from-db-${id}`;
  const value = cache.getOrCreate(key, () => api.getById(id));
  return value;
}

```

**Comment by isaacs** [comment]
Setting the fetch method on each call to fetch would mean that we can't guarantee that it's the same kind of thing.  It's not going to be feasible to have a map that keys on two things (ie, the key provided and also the fetch method).  You can do this by creating two different caches, or providing a fetchMethod that knows what to do with different sorts of keys.

```js
const dbAndApiCache = new LRU({
  // ... max, maxSize, ttl, etc...
  fetchMethod: async (key, options) => {
    if (/^from-api-/.test(key)) {
      return api.getById(key.substr('from-api-'.length))
    } else if (/^from-db-/.test(key)) {
      return db.getById(key.substr('from-db-'.length))
    } else {
      throw new Error('key must match "from-api-${id}" or "from-db-${id}"')
    }
  },
})
```

**Comment by isaacs** [comment]
@daniele-pini The problem is that LRUCache assumes that the key completely identifies the thing being cached.

What that means is that if you fetch() for a given key, and then (before it's resolved) make another fetch() for the same key, we can just return a promise that resolves to the same value once it arrives, rather than make a second query.

Consider this very simplified case, if we _did_ allow setting the `fetchMethod` for a given request:

```ts
const c = new LRUCache<number, number>({
  max: 10,
  fetchMethod: async (n) => n,
})

const results = await Promise.all([
  c.fetch(3), // expect 3
  c.fetch(3, { fetchMethod: async (n) => n * n }), // expect 9, actually 3
  c.fetch(3, { fetchMethod: async (n) => n + n }), // expect 6, actually 3
])
```

In this case, the results will be `[3, 3, 3]`, because the first fetch is in progress and hasn't yet been resolved when the other two fetch() calls come in.  So, you get the results of the first fetchMethod, even though you provided a different fetchMethod.  There is no way for TS to catch this, because of course all three take a number and return a number.

This inflight behavior is extremely important for many use cases where you have a slow backend that you want to cache.  If a fetch goes out, you don't want _another_ fetch to go out which also has to wait for the fetchMethod to make multiple calls to the backend, that's slow and inefficient.

There's no way to satisfy _both_ the contract that the fetched result will be that resolved by the fetchMethod, _and_ that only one fetch will be in progress for a given key at a given time, without having the cache differentiate between the fetchMethod in use for a given fetch() call.

It _is_ possible, of course, to put this logic in the fetchMethod itself, or to use a different cache for each of your alternate fetchMethods.  LRUCaches are a tiny bit slow to instantiate, but very cheap and fast at runtime, so there's really no harm in having multiple instances.

Multiple cache example, this would also work if the caches were defined in different modules, for example.  So it's a bit more complex, but also more flexible:

```ts
// ONE of these will probably work, but a backend might be down, or
// not support the path specified, or whatever.

const backends = [
  'https://api1.example.com/',
  'https://api2.example.com/',
  'https://api3.example.com/',
]

const options = {
  max: 1000,
  ttl: 1000,
  allowStaleOnFetchRejection: true,
}

// create a cache for each backend
const caches = backends.map(backend => new LRUCache({
  ...options,
  // we might get aborted because another provider found it,
  // but that shouldn't mean we drop what we have.
  noDeleteOnFetchRejection: true,
  noDeleteOnFetchAbort: true,
  fetchMethod: async (key, _oldValue, { signal }) => {
    const url = new URL(key, backend)
    const res = await fetch(url, { signal })
    return await res.json()
  }
}))

// create the exported parent cache
export const service = new LRUCache({
  ...options,
  fetchMethod: async (key, _oldValue, { signal }) => {
    // bonus efficiency, cancel any pending requests when we get an answer,
    // so we only cache in one of them.  If you'd prefer more cache resilience
    // at the cost of perhaps unnecessary network/CPU usage, don't do this.
    const ac = new AbortController()
    signal.addEventListener('abort', () => ac.abort(signal.reason))
    const foundSignal = ac.signal
    const result = await Promise.any(caches.map(c => c.fetch(key, { signal: foundSignal }))
    ac.abort(new Error('found'))
    return result
  }
})
```

Single cache example, differentiating in the fetchMethod, little bit simpler, but it does mean that all the logic has to be in one place:

```ts
// ONE of these will probably work, but a backend might be down, or
// not support the path specified, or whatever.

const backends = [
  'https://api1.example.com/',
  'https://api2.example.com/',
  'https://api3.example.com/',
]

// create the exported parent cache
export const service = new LRUCache({
  max: 1000,
  ttl: 1000,
  allowStaleOnFetchRejection: true,
  fetchMethod: async (key, _oldValue, { signal }) => {
    // bonus efficiency, cancel any pending requests when we get an answer,
    // so we only cache in one of them.  If you'd prefer more cache resilience
    // at the cost of perhaps unnecessary network/CPU usage, don't do this.
    const ac = new AbortController()
    signal.addEventListener('abort', () => ac.abort(signal.reason))
    const foundSignal = ac.signal
    const result = await Promise.any(backends.map(async b => {
      const res = await fetch(key, { signal: foundSignal })
      return await res.json()
    })
    ac.abort(new Error('found'))
    return result
  }
})
```

Of course you could also use the "choose in fetchMethod" or "use multiple caches" to do whatever other kind of differentiation based on the key that you wanted.  But in order to get the performance benefits of inflight synchronization and efficient caching, you do need to do a bit of up front thinking about how and what you are caching.  In general, I've found it's best to have a caching layer as close to the slow "thing" as possible, and make it as transparent as possible to the caller as you can, rather than make the caller have to know about what caching is happening.  There are of course huge exceptions to this, which is why for example `ttl` and `allowStale` and other options can be specified by the caller, because a use case might require that you _sometimes_ need to pierce the caching layer and get the latest data, but other times you're perfectly fine with stale data no matter how old it is.

> This practically forces my to cache promises directly using set/get right now...

Can you share more about what it is you're caching and how you'd use a callsite-specified `fetchMethod`?

**Comment by daniele-pini** [comment]
@isaacs, thanks for your prompt reply.

I need to expose a cache to client modules, so I can't assume anything about client modules' logic - injecting the logic in the cache would break the single-responsibility principle.

Creating a "cache-of-caches" means that I can't easily control the "max" amount of cached objects anymore. Ttl control would also be fragmented - I'd have to set one for each "sub-cache" objects (otherwise they leak), but that way I'm overriding the actual cache items's ttl. It's not an ideal solution.

My use case would be similar to this:
```

// module cache.ts
export const c = new LRUCache<number, number>({
  max: 10
})

// module stats.ts
async function getStats(num: number): Promise<number[]> {
  return await Promise.all([
    // Cache keys associated to the fetchMethod *by construction*
    c.fetch(`ident-${num}`, { fetchMethod: async () => num },
    c.fetch(`square-${num}`, { fetchMethod: async () => num * num },
    c.fetch(`sum-${num}`, { fetchMethod: async () => num + num },
  ]);
}
```

The point of contention is clearly here:

> There's no way to satisfy both the contract that the fetched result will be that resolved by the fetchMethod, and that only one fetch will be in progress for a given key at a given time, without having the cache differentiate between the fetchMethod in use for a given fetch() call.

There are two things to note here:

- You _could_ actually satisfy both contracts, you just need to store the `fetchMethod` used to calculate the fetch item with the fetch result promise. Not on the _keys_ side, but on the _values_ side of the cache's internal map. If a `fetch` tries to access the same key with a different `fetchMethod`, compare the methods and throw an error if they differ.

  This would still not solve my problem - note how in my snippet above I create a function every time.

- Let's say letting users specify the `fetchMethod` on `fetch` invocation means that the LRU cache can't ensure the consistency of the fetching logic. That doesn't mean that there's no value in letting users take control of the consistency ensurances themselves _if they want_.

  You could just mark the specified option as "dangerous" like React does - say, add an option together with `fetchMethod`, say `dangerouslySkipFetchMethodCheck` to let users take explicit control of consistency checks.

Consider that the normal cache usage (without fetch) already lets you store objects without knowing how they were calculated - this would be the same except that the lru-cache takes care of async coordination itself, sparing clients some work.

For example, I can still cache result promises like this and get similar results:
```
async function getStats(num: number): Promise<number[]> {
  let identPromise = c.get(`ident-${num}`);
  if (!identPromise) {
    identPromise = (async () => num)(); // This is silly, I know - assume the logic could be declared before
  }

  let squarePromise = c.get(`square-${num}`);
  if (!squarePromise) {
    squarePromise = (async () => num * num)();
  }

  let sumPromise = c.get(`sum-${num}`);
  if (!sumPromise) {
    sumPromise = (async () => num + num)();
  }

  return await Promise.all([
    identPromise,
    squarePromise,
    sumPromise
  ]);
}
```

But if lru-cache did this for me that would be a nice improvement.

**Comment by isaacs** [comment]
Oh! Hey, I just realized an obvious solution to this, just use the `context` object.

Of course, you have to be reasonably sure that the key _will_ uniquely always have the same kind of fetcher, or you'll get some very weird mismatches, but this would work really easily, and you'd have all the consistent maxes and stuff that you want:

```ts
// Note: shown with version 8.x API, the context is a little bit different in v7
const c = new LRUCache<string, number, (string) => Promise<number>>({
  stale: 1000,
  max: 1000,
  fetchMethod: async (key, oldValue, { context, signal }) => {
    return context(key, { signal })
  },
})

// just an example showing cleanup on abort
const squareFetch = async (key:string, { signal }: { signal: AbortSignal }):Promise<number> => {
  assert(key.startsWith('square-'))
  return new Promise<number>(res => {
    const t = setTimeout(() => {
      res(+(key.substring('square-'.length)))
    }, 100)
    signal.addEventListener('abort', () => {
      res(0)
      clearTimeout(t)
    })
  })
}

// this one doesn't do cleanup
const idFetch = async (key:string):Promise<number> => {
  assert(key.startsWith('identity-'))
  return +(key.substring('identity-'.length))
}

// this one lives dangerously
const doubleFetch = async (key:string):Promise<number> =>
  +(key.substring('double-'.length)) * (+(key.substring('double-'.length)))

const sq = await c.get('square-5', { context: squareFetch }) // 25
const id = await c.get('identity-5', { context: idFetch }) // 5
const db = await c.get('double-5', { context: doubleFetch }) // 10
```

Does that work for you?

The caveat, of course (which is spelled out in the docs on using a fetch context as well) is that the cache still assumes that the key completely identifies the thing being fetched, so if you did this:

```ts
const id = await c.get('identity-5', { context: idFetch }) // 5
const db = await c.get('identity-5', { context: doubleFetch }) // also 5, inflight synced
```

then that second call would still just piggyback on the first.

You can put literally anything you want in the context argument, so idk why that didn't occur to me initially.  But at least it's got enough bright warnings around it and it's quite a bit more opt-in, so I don't feel like it's making the same kind of promises that a per-request `fetchMethod` option would.

**Comment by isaacs** [comment]
By the way, I really would not cache Promise objects like that.  I've seen some bizarre and surprising performance and memory leak issues result from it.  It's best to let them be garbage collected as soon as possible after they're resolved.

You could do this by making the cache in your example an `LRUCache<string, number | Promise<number>>` and then doing something like:

```ts
  const [id, sq, sum] = await Promise.all([
    identPromise,
    squarePromise,
    sumPromise
  ])
  cache.set(`ident-${num}`, id)
  cache.set(`square-${num}`, sq)
  cache.set(`sum-${num}`, sum)
  return [id, sq, sum]
}
```

**Comment by daniele-pini** [comment]
Thanks @isaacs, sorry for the late reply - busy travelling.

Using `context` the way you outlined is ok for me, it does precisely what I need. Thanks for the tip!
And thanks for the promises vs cache warning, it's news to me. Will have to do some reasearch about it...

Cheers!
