### ISSUE TITLE
Support browser

### ISSUE THREAD

**Issue by Minilo-ng** [isaacs/node-lru-cache#248]
The project name is 'node-lru-cache', however it not depends any nodejs lib. Is there any plan to build an umd bundle for web developers?

**Comment by isaacs** [comment]
It's heavily optimized for node, and while it _should_ work in any browser environment that you can manage to get a commonjs module into (since it's zero-deps), it's likely that it won't be quite as performant or optimized there.

There's no plans to ship this in alternative formats or bundles, and the path of least resistance for users is to leave it as-is, but (as with #253), patch welcome if it's unobtrusive.

**Comment by isaacs** [comment]
You can use the mjs export to do this:

```html
<!doctype html>
<body>

<script type="module">
import LRUCache from "https://unpkg.com/lru-cache@7.15.0/index.mjs"
const c = new LRUCache({ max: 10 })
c.set(1, 1)
c.set(2, 2)
console.log(c.get(1))
console.log(c.get(2))
document.body.innerHTML = `<pre>${JSON.stringify(c, null, 2)}</pre>`
</script>
```
