### ISSUE TITLE
Custom underlying storage and item cacheable flag

### ISSUE THREAD

**Issue by otakustay** [isaacs/node-lru-cache#252]
We're developing a system to cache immutable http response by url, `lru-cache` is a best choice for us, however I'm confused if we can do a little cusomization on the cache machanism.

First, to cache a large amount of data, we have a second-layer cache to store response data in file system, I didn't find any option to allow `lru-cache` to have a custom underlying system, #174 and #29 seems to give a solution on redis but is still not suitable for using file system caches like `cacache`, https://github.com/npm/cacache/issues/20 is suggesting to use `async-cache` package which is deprecated and is saying we should use `lru-cache` instead.

I think we may be able to do this by subclassing `Cache` and override some methods, are there some core methods could be customized to delegate cache to some storage other than in memory?

Another issue we encountered is that our response data vary from 1KB to 50MB, to ensure our cache with a fixed `maxSize` option can store an estimated count of entries, we'd like to skip caching when `fetchMethod` resolves to a response larger than 1MB, but it seems no options like `cachable(key, value)` or `maxCacheableSize` are related to this, still, is this something we can customize by overriding some methods of `Cache` class?

Thanks.

**Comment by isaacs** [comment]
You can definitely subclass the LRUCache class to back it persistently.  I did this recently to store cache dumps in postgres: https://gist.github.com/isaacs/29d34dfddd4f8f10e60f97de3e130e04 (I intend to make this a standalone module, it's got quite a few remix-isms in that gist, but you can use it to get some inspiration.)

There isn't any way to store each _item_ as a separate file system entry, but that wouldn't be too hard to accomplish.  The hazard I would want to keep in mind is that file system writes and deletes can get rather slow, so you might want to make them "best effort".  If there's an easy way to shard your data, you could perhaps have a collection of BackedCache-style LRUCache objects that each write their `cache.dump()` json to disk, which would avoid the hazard of thrashing your file system with tons of tiny writes.

A `maxEntrySize` option is a good idea!  I'll add that.  Currently, it's smart enough to not try to store something that's above the `maxSize` (since that would mean it would have to immediately everything to stay below the limit).  You could _sort of_ hack it today by doing something like this:

```js
const cache = new LRUCache({
  maxSize: 100 * 1024 * 1024, // 100mb
  sizeCalculation: (item) => {
    // if the item length is > 1mb, don't even bother
    return item.length < 1 * 1024 * 1024 ? cache.maxSize + 1 : item.length
  },
})
```

I would not suggest adding a `cacheable()` general purpose filter method, since that would have to be called for every item, and so you'd be taking a second performance hit in addition to the sizeCalculation method.

**Comment by isaacs** [comment]
Closing now, since `maxEntrySize` is an option, and there's not much more to do in this module for this issue.

Thanks again for the suggestion!
