### ISSUE TITLE
Dispose function is getting called even if max limit or max age of cache items is not reached

### ISSUE THREAD

**Issue by tdk1710** [isaacs/node-lru-cache#256]
We are using lru-cache v5.1.1 npm package in our application to store mongodb connections. If mongo connection is already available in the cache, then are getting the connection from cache else we are creating new mongo connection and storing it into cache. We are observing that when we are trying to get a connection object from a cache the dispose function is getting called even if the max limit or max age of cache items is not reached. We noticed from our application logs that the issue seems to be coming when multiple requests are trying to get a connection object from cache almost at the same time. There is a difference of milliseconds between requests.

We have defined our cache with below configurations:

```
const LRU = require("lru-cache")
    , options = {
        max: 100
        , dispose: function (key, n) { n.close() }
        , maxAge: 120000
    }
```

At high level, our logic is implemented like below.

```
let connObj = cache.get(key);
if (!connObj){
	connObj = new ConnectionObj(); // This code block seems to be executing for 2 requests when requests are coming at the same time in difference of milliseconds. Ideally, it should execute for first request only and for second request it should take connection object from cache.
        cache.set(key, connObj)
}
```

Could you please let us know if similar issue related to dispose function is observed earlier. Do we need to use await with cache.set ?

**Comment by isaacs** [comment]
v5.1.1 is 4 years old.  Please update.  There are a few API changes noted in the changelog, but they're relatively minor; the only change from the code you posted is that the signature of `dispose()` has changed to `dispose(value, key, reason)` instead of `dispose(key, value)`.  Performance, reliability, and timing precision are *vastly* improved.  (And in fact, if acquiring a connection _is_ asynchronous, you can provide an asynchronous `fetchMethod`, and use `const connection = cache.fetch(key)` to ensure that any parallel connection creation attempts are deduplicated.)

So, in v7, instead of this:

```js
let connObj = cache.get(key)
if (!connObj) {
  // ie, if this is actually connObj = await getConnection(), that's your problem
  connObj = new ConnectionObj()
  cache.set(connObj)
}
```

you'd do this:

```js
const cache = new LRUCache({
  fetchMethod: async (key) => await getConnObjOrWhatever(key),
  max: 100,
  maxAge: 120000,
  dispose: (conn, key, reason) => conn.destroy(),
})

/// ....

// even if you make the same cache.fetch() multiple times
// in rapid succession, it'll only call fetchMethod once for a
// given key, and just return the same promise to each of them.
const connObj = await cache.fetch(key)
```

If the problem persists in the latest version, I'd be happy to take a look.  v7 and above is basically a whole different module; even if this is found to be a bug in lru-cache v5, I won't be fixing it there.

To answer your questions: No, you do not need to use `await` on `cache.set`, because the function does not return a Promise.  If the `get()` and `set()` do not occur in the same JavaScript tick (for example, if getting a new connection is asynchronous), then you could have a situation where you're calling `get()` multiple times, all returning undefined, and then calling `set()` multiple times unnecessarily.

If the `maxAge` has expired, then it won't be noted (unless you use `ttlAutopurge: true` in the cache settings, but that doesn't exist in v5.)
