### ISSUE TITLE
Purging stale cache hangs

### ISSUE THREAD

**Issue by LaurensRietveld** [isaacs/node-lru-cache#278]
LRU-Cache may hang with 100% cpu usage when purging stale cache.
See below for a MWE:

```js
const lru = new LRU({
  ttl: 100,
  maxSize:100,
  sizeCalculation: () => 1
});
lru.set('key1','value1')
lru.set('key2', 'value2')
setTimeout(() => lru.purgeStale(), 200)
```

Some observations:
- There aren't issues when only adding 1 item to the cache
- There aren't issues when using `max` instead of `maxSize`
- This seems to be caused by an infinite loop over `rindexes` in the `purgeStale()` function

**Comment by isaacs** [comment]
Ah, this was introduced in c29079d, when `max` became optional.

With that change, when there are no entries in the array, and the `next` and `prev` arrays are normal `Array` rather than a UintArray, the default unset value is `undefined`, rather than `0` (or some other previously used number).

So then it checks to see if the index is valid (and if not, it stops the iteration) by calling this:

```js
  isValidIndex(index) {
    return this.keyMap.get(this.keyList[index]) === index
  }
```

Since the index is `undefined` (and that isn't a valid array offset), `this.keyList[index]` returns undefined, which isn't found in the keymap of course, so that returns `undefined`, which is equal to the index, since they're both undefined.

But `undefined` isn't a valid key value anyway! So the fix is pretty straightforward.  But that's why it doesn't happen when `max` is set, because in that case, we pre-allocate a UintArray to use as the store of indexes, and they'll _always_ be a number, rather than `undefined`.

There have to be at least _two_ entries to trigger the bug, and all of them have to be deleted in the loop over the entries, and the iteration has to be in reverse so that the links don't get changed as we iterate over it (not sure why that is yet, it's possible that's a code path that was playing fast and loose on the assumption that the `next`, `prev` and head/tail would also always be numbers).

Even more minimal repro:

```js
const lru = new LRU({
  maxSize:2,
  sizeCalculation: () => 1,
});
lru.set('x', 'x')
lru.set('y', 'y')
for (const key of lru.rkeys()) {
  lru.delete(key)
}
```
