### ISSUE TITLE
[bug] throw TypeError: Cannot read from private field at __accessCheck when used in vue3 + vite  + pinia store

### ISSUE THREAD

**Issue by joyexpr** [isaacs/node-lru-cache#286]
version 8.0.3, throw TypeError: Cannot read from private field at __accessCheck when used in vue3 + vite  + pinia store state

version 7.8.13 is normal

**Comment by isaacs** [comment]
There's nothing called `__accessCheck` in lru-cache.  Please share a stack trace showing where in lru-cache this is happening.

**Comment by joyexpr** [comment]
it seems to be js proxy problem, lru-cache(version 8.*) is not support as reactive state.

as I move the cache variable out of the vue3 pinia state to be  a normal non-reactive variable, it works fine

**Comment by isaacs** [comment]
I've never heard of pinia.  If there's something they need changed in LRUCache to play nice with their system, I'm of course willing to consider it if they request it, but not much I can do about this otherwise.

**Comment by isaacs** [comment]
Yeah, so, some additional care must be taken when wrapping an object in a Proxy if it uses private properties. You can't just pass through `get` calls for methods to the source object, because if those methods use hard-private properties, they'll end up being called in the this-context of an object whose class didn't define those private properties.

So, yes, it is a change made to LRUCache that made it incompatible with this sort of usage, but also, it's a shortcoming in the Proxy usage that depends too intimately on the internal details of the object it's wrapping. Ie, it requires that the source object doesn't reference any hard-private properties from public methods, and if you don't reference them from any exposed method, then why are they even there?

Breaking change on semver major update, sorry, that's how it goes. The consuming code has to change. Frankly, it's a very brittle approach, and lucky that the change happened in a semver major update, since many would not consider the addition of internal private members to be a breaking change at all.
