### ISSUE TITLE
v8: TypeScript types misrepresent CJS exports

### ISSUE THREAD

**Issue by nwalters512** [isaacs/node-lru-cache#289]
Consider the following code:

```ts
const { LRUCache } = require('lru-cache');
new LRUCache({ max: 10 });
```

This type-checks correctly, but fails at runtime:

```
Uncaught TypeError: LRUCache is not a constructor
```

Indeed, `LRUCache` is `undefined`.

I tried changing it to this:

```ts
const LRUCache = require('lru-cache');
new LRUCache({ max: 10 });
```

This works at runtime, but TypeScript now reports an error:

```
This expression is not constructable.
```

Ultimately, the following code worked at runtime and type-checked correctly, but it's a little unwieldy:

```ts
const LRUCache = require('lru-cache').default;
new LRUCache({ max: 10 });
```

---

I suspect that dropping the `types` field from `package.json` would fix this. That would allow TypeScript to just resolve the `dist/cjs/index-cjs.d.ts` file that's adjacent to the `dist/cjs/index-cjs.js` file referenced in the `main` field in `package.json`.

**Comment by isaacs** [comment]
The reason for this weird slight of hand is that combining TypeScript, Node, ESM, and CommonJS all in one place makes for a lot of really annoying edge cases if you just want to ship a default export and have all users be able to get that default export in the most obvious way.

> I suspect that dropping the types field from package.json would fix this.

Sadly, no, it would not.  It ends up with quite a few cases (at least in neovim) where all the type hinting that you get is that `LRUCache` is `class LRUCache`, which is less helpful than anyone wants.  Typedoc gets very confused by the Object.assign, and the output is just a weird thing called `_default`.  And I'm not willing to force cjs users to tack a `.default` onto everything, it's so ugly and weird.

The somewhat less inelegant solution is to not have a default export at all, so that the cjs shim isn't needed, which I've been moving towards in most new modules I create.  But for things that have been a default-export for a long time, it really throws people off.

**Comment by nwalters512** [comment]
Thanks for taking a look at this @isaacs! Unfortunately `const LRUCache = require('lru-cache')` still fails to type-check with the new version, but using the named `LRUCache` property on exports works great. I generally prefer named exports anyways 🙂 

To elaborate on my "what if we just dropped the `types` field" comment: I suggested that because `types` currently points to the ESM types, even though `main` points to CJS code. So even though `dist/cjs/index-cjs.js` contains types that correctly describe the CJS entrypoint, they're never used because you've hardcoded the types to point to the ESM entrypoint. I tested removing `"types"` locally in VSCode + `tsc` and it actually worked great; it's a shame that neovim seems to not resolve types in the standard TypeScript way.

I appreciate how difficult it is to get TS/Node/ESM/CJS all playing well together. Thanks for doing your best to make it work 🙏

**Comment by isaacs** [comment]
Oh! you mean the top-level `types` field?  That should be overridden by the `types` in `exports` anyway, it's only there for node versions (and tsc pretending to be node versions) that didn't support `exports`, at least that was my understanding.

The matrix of consumers to support is:
- various versions of tsc
- various versions of tsserver (VSCode and neovim use the same tsserver internally, so if there's a difference, it's likely due to different ts versions, not different editors)
- webpack
- typedoc

What version of typescript are you using?  `npm ls typescript` should show it.

Do you have the same issues with `minimatch` or `mkdirp`?  They use the same kind of pattern, I wonder if there's something here I'm overlooking. (Ie, if they work and lru-cache doesn't, then something's different.)

**Comment by isaacs** [comment]
Node version would be good to know, as well, that might be a factor.  And the `moduleResolution` in `tsconfig.json`.

**Comment by isaacs** [comment]
So playing with this a bit more, it seems like `require()` in typescript will _always_ type as `any` (but ts wants you to use `import` always, and let it rewrite to require or import based on tsconfig, so that's maybe not surprising).

But yeah, using `require()` in js does seem to get confused when there's a top-level `types` field.

Thanks for being persistent on this, I think you're right.  Which is annoying, because now I have a bunch of stuff to republish. 😂

I think I'm gonna just say the priority is "people writing code", and removing the top-level `types` is a net improvement for that use case.

**Comment by nwalters512** [comment]
Great point about `"moduleResolution"`! I was using the default `"classic"` value. Setting it to `"nodenext"` got me closer, but that actually revealed a different issue: the `"exports"` in this package appear to be pointing to the wrong types for the `"require"` condition.

https://github.com/isaacs/node-lru-cache/blob/eb177f517a32ba013f2a5fefe7748422536ca632/package.json#L51-L54

I believe line 52 should be `"./dist/cjs/index-cjs.d.ts"` instead. Combined with `"moduleResolution": "nodenext"`, this worked great for me locally.

You may want to make this change for the `./min` export as well; I didn't check if that's compiled from the CJS entrypoint.

**Comment by isaacs** [comment]
So the problem here is that without "fibbing" about the types, you get this:

<img width="1272" alt="Screenshot 2023-04-05 at 11 40 41" src="https://user-images.githubusercontent.com/9287/230174975-94c33d2a-3e53-4683-b6e9-44ceb2b2fd8b.png">

By setting it to the "full" export that it's mocking, you get this:

<img width="1281" alt="Screenshot 2023-04-05 at 11 41 19" src="https://user-images.githubusercontent.com/9287/230175035-24501a33-caa2-42c3-ab6a-b54a1a4185c6.png">

which is clearly an improvement.

Another concern here, and the reason why the `exports` types for the cjs shims are pointed to the types for the modules they're copying: https://github.com/isaacs/minimatch/issues/194

So I think there's also some difference between `"moduleResolution": "node"` and `"moduleResolution": "node16"` here.

**Comment by isaacs** [comment]
> You may want to make this change for the ./min export as well; I didn't check if that's compiled from the CJS entrypoint.

It is compiled from the CJS entrypoint, but it bundles both modules into one.

And really, the CJS entrypoint is just:

```ts
import LRUCache from './index.js'
export = Object.assign(LRUCache, { default: LRUCache, LRUCache })
```

So, it is literally the same exact type as what `./index.js` exports...

Still so resentful about Node, TS, and TC39 all deciding to go their own directions on this.

**Comment by isaacs** [comment]
Ok, flipping the TS/ESM/CJS tables, no more default exports from any of my modules moving forward.  I'm done.  Upgrade to the latest, do `import { LRUCache } from 'lru-cache'` or `const { LRUCache } = require('lru-cache')`, and this problem goes away.
