### ISSUE TITLE
`set(k, undefined, { noDisposeOnSet: true })` still calls `dispose`

### ISSUE THREAD

**Issue by SamWilsn** [isaacs/node-lru-cache#291]
I expected overriding with `undefined` to respect `noDisposeOnSet` the same way overriding with any other value does.

**Comment by isaacs** [comment]
As stated in the docs, `set(k, undefined)` is just an alias for `delete(k)`.

The cache will not cache "undefined".

See #290

**Comment by isaacs** [comment]
https://github.com/isaacs/node-lru-cache#storing-undefined-values

**Comment by SamWilsn** [comment]
Yep! I saw that. I don't want to cache `undefined`. I want to `delete` an item without calling dispose. I guess you could call it a `take` operation.

This issue is about the inconsistency between `set(key, 3, { noDisposeOnSet: true })` and `set(key, undefined, { noDisposeOnSet: true })`. The former does not call `dispose` but the latter does even though I asked it not to.

**Comment by isaacs** [comment]
That's because [`set(key, undefined)` just calls `delete(key)`](https://github.com/isaacs/node-lru-cache/blob/main/src/index.ts#L1597-L1600), and there's no `noDisposeOnDelete`.  Maybe there should be?

Another option is to actually track that a key is holding an undefined value, by keeping a sigil value internally. (So it'll contribute to the `max` count, `has()` will return `true`, etc.) But that's a bit complicated, especially a pita getting the types right internally, since now things can be `V | symbol` if it includes undefined, etc.

**Comment by SamWilsn** [comment]
I completely understand the technical reasoning behind not implementing `noDisposeOnSet` for `undefined`. I saw in the source that `set` literally calls `delete`:

https://github.com/isaacs/node-lru-cache/blob/4134a83cc65f4acd90010c880e9ad8c401588003/src/index.ts#L1597-L1600

I'm being a bit picky about the interface being inconsistent, that's all. IMHO, `set` + `undefined` + `noDisposeOnSet` should either: not call `dispose`, or throw an exception.

---

Why separate `noDisposeOnSet` and  `noDisposeOnDelete`? Are there cases where you'd want to do one, but not the other?

**Comment by isaacs** [comment]
> Why separate noDisposeOnSet and  noDisposeOnDelete? Are there cases where you'd want to do one, but not the other?

Apparently yes ;) There's never been a case where someone asked to suppress the dispose function on `delete`, but `noDisposeOnSet` came about because people wanted to be able to update the value without triggering the dispose function.

It makes sense, eg, if you're using the `dispose` function to do reference counting, or if the key is the thing being disposed. In that case, yes, `delete` (whether eviction or explicit) should _always_ trigger a disposal, but reusing the same key for a new value should not.

**Comment by SamWilsn** [comment]
Heh :P

I meant in the options type for set, not generally. More specifically my question is whether there is a use case where you'd have:

```javascript
set(key, value, { noDisposeOnSet: true, noDisposeOnDelete: false })
```

or

```javascript
set(key, value, { noDisposeOnSet: false, noDisposeOnDelete: true })
```

where you'd want the behaviour for `value === undefined` and `value !=== undefined` to differ, or would this be sufficient:

```javascript
set(key, value, { noDispose: true })
```

---

Thinking about this a bit more, maybe the correct approach is to just add a `take(key: K): V | undefined` function that is `delete` but returns the value without running dispose?

**Comment by SamWilsn** [comment]
Maybe I'm running afoul of the [XY Problem](https://en.wikipedia.org/wiki/XY_problem).

I'm using `lru-cache` to hold several in-flight requests, up to some limit. If the request is evicted because of cache pressure, I want to send an error reply to the requester (currently with `dispose`.) On the other hand, if the request completes I want to remove the request from the cache and reply with the non-error response.

**Comment by isaacs** [comment]
So, I think the way to get to a truly consistent API for `set(k, undefined)` would be to use an "undefined value" sigil.  The only reason I backed away from that is that it means a updating a bunch of internal types.  Basically, everywhere I currently use the `V` template type internally, I'd have to replace that with `undefined extends V ? Exclude<V, undefined> | typeof UndefinedValueSigil : V`, and any time that a value is exposed to the user, it'd have to check if it's the undefined value sigil, and replace with `undefined`. The types, meh, whatever, that's a search and replace, but the value checks would add some cycles in a few extremely hot paths, so that's somewhat undesirable.

On your XY Problem: I think you can lean on AbortSignals for this, instead of a dispose method, and that might give you a better result.  Plus then if you make the same request, 

Would this work?

```ts
// allow up to 100 
const cache = new LRUCache<string, any>({
  max: 100,
  fetchMethod: async (key, _, { signal }) => {
    const res = await fetch(`https://api.server.com/v1/${key}`, { signal })
    return await res.json()
  }
})
export const getThing = async (key: string) => cache.fetch(key, { forceRefresh: true })
```

If cache pressure evicts the request mid-fetch, it'll trigger the abort signal, and the caller will see it fail with an `Error: evicted`.  The `forceRefresh` will tell it to always fetch a new thing, even if the current one is not expired (which it never will be, because there's no TTL.)  You might want to catch the error and provide a more useful message than `evicted`, but that should do what you're describing with a lot less hassle.  And if you want to have a "give me the most recent result, don't make a new request unless necessary" method, you can just drop the `forceRefresh` flag.

**Comment by SamWilsn** [comment]
> So, I think the way to get to a truly consistent API for `set(k, undefined)` would be to use an "undefined value" sigil.

I'm rather new to this codebase (and TS/JS in general) so I must admit this is beyond my current understanding.

> Would this work?

Hm, something like that might work. I'll have to play with it a bit. My current key isn't sufficient to make the request, but I can probably move stuff around. If you're curious, [this is where I'm using `lru-cache`](https://github.com/wallet-test-framework/framework/blob/master/server/src/client.ts#L81). I just noticed a few bugs in that file so consider it a prototype at the moment :sweat_smile:

**Comment by isaacs** [comment]
You can probably rip out a lot of what that file is doing, since LRUCache already collapses in flight `cache.fetch()` calls for the same key.  The important thing is getting a key that can fully identify the thing to be fetched, if you can do that, then you can lean on the cache a lot more and let it do the heavy lifting.
