### ISSUE TITLE
Breaking change in handling of `undefined` values

### ISSUE THREAD

**Issue by ZzZombo** [isaacs/node-lru-cache#292]
Is there a good reason why you do not use a sentinel object yourself? It should be trivial for you to use a unique object, `const notPresentValue = {}` should do the trick, or if you feel fancy you could use a `Symbol`. This is better handled by your module rather than its consumers, there is no good reason why all of them have to reinvent the wheel for this (in addition to having to review all places where `undefined` gets stored) when it could be done a single time by you as the developer.

**Comment by isaacs** [comment]
What's the "breaking change" you're referring to? Do you mean not allowing the storage of `undefined`, which landed in version 8?  It's worth noting that, while it didn't _stop_ you from storing undefined in v7 and before (either in the code or the types), there has been for quite some time a few edge cases where storing undefined or null could cause incorrect behavior.  So it was a bugfix, albeit one that required changing the exposed interface.

> Is there a good reason why you do not use a sentinel object yourself?

Complexity and performance, mostly.  It's probably solvable, just more work to be done than it might appear at first.  Easier to just not store undefined (or treat the storage of undefined as a delete, which is what LRUCache does now).

Do you have a use case where you need to store `undefined` and have that value tracked in the cache?  Can you elaborate on what you're doing, why this is valuable for you?

**Comment by ZzZombo** [comment]
I want to address primarily the `undefined` as value change. Previously `lru-cache` was more or less a drop-in replacement to `Map` and the latter stores them just fine. When choosing the package for this task compatibility with the `Map` object was a requirement as it's what was used beforehand for storing results. I have a ORM middleware in my application, I now have to review all the arbitrary places where it could return `undefined` as a field value before storing query results if I ever want to update the dependencies. And yes, the lack of a field vs `undefined` as its value does have its own implications upstream for the consumers I can't foresee just yet.

**Comment by isaacs** [comment]
@legobeat What are you doing to trigger that issue?  `new LRUCache<number, number, undefined>({max: 1})` works fine for me.

@ZzZombo An LRUCache is not a Map. Items may fall out of it at any time, so it's semantically quite different, even though it presents a similar API surface, because it has storage bounds. In previous versions, if you put `undefined` into the cache, then it could cause incorrect behavior, because it uses `undefined` to mean that a key or value is not found, an `undefined` return from a `fetch()` is not stored, etc.  JavaScript doesn't differentiate between `void` and `undefined` in any particularly useful ways, so there's not much I can do about it.  If you're putting undefined in the cache in previous versions, then the internal counts and linked lists can get out of sync.  That's not good.

Storing a sentinel value when I see `undefined` is theoretically an option, yes, but it's a huge pain.  The internal types (where it has to handle the sentinel object) get really convoluted, it involves a lot of value checks that reduce performance in hot paths and offer no value in the vast majority of cases.  And, it would mean making a very tricky decision about the case of aborted fetches, where we do get `undefined` and currently semantically treat it as "do not store a value", which is bound to be incorrect sometimes.  If I was going to go that route, the only way to do so that's really feasible is to export a subclass of LRUCache that allows storing undefined values, and that's just more code to manage, requires significant internal refactoring, etc.
