### ISSUE TITLE
stale status with TTL remaining

### ISSUE THREAD

**Issue by alwendt** [isaacs/node-lru-cache#293]
I'm using 7.18.3 and I'm seeing this entry status in the logs for a stale entry:

"aws_account_name":"sfly-aws-legacy-dev","container_id":"4da59627031a","container_name":"ecs-pip-data-beta-434-pip-data-e4fbcaa4d79de3ce9e01","log":"get succeeded entryStatus = {\"ttl\":600000,\"start\":1682117929070,\"now\":1682120523437,\"remainingTTL\":3194367,\"get\":\"stale\",\"returnedStale\":true}","SERVICE":"pip-data","SFLY_ENV":"BETA","MANAGED_BY":"commerce-sitestore","DEPLOYMENT_TRACK":"stable","task_id":"b4bbe8ca44d44e5eb114ee400c6f3f96"}

I don't understand how an entry can be stale with the big TTL.  

I have allowStale = true and noDeleteOnStaleGet = true

**Comment by isaacs** [comment]
I believe that's a little bit misleading. What it's saying is just that fetch returned the entry that it already had from the cache, but it's the same code path and basically v0 of the status object tracking. But you're right, it's right there in the object, `"remainingTTL":3194367` so it had another 53 minutes or so to live.

I recommend upgrading to the latest version. The only significant breaking changes are that you can't store `undefined` in the cache, and you have to do `import { LRUCache } from 'lru-cache'` instead of `import LRUCache from 'lru-cache'`.

**Comment by isaacs** [comment]
What _is_ a little bit weird to me is that your `remainingTTL` is _way_ higher than your `ttl` setting.  Are you setting the ttl per-item explicitly?

**Comment by alwendt** [comment]
No, I checked all the set calls and they are just taking key and value.

**Comment by isaacs** [comment]
Oh the bug here is just the "remainingTTL". It's subtracted wrong. Look at start and now. That number should be negative.

**Comment by isaacs** [comment]
Like, the `remainingTTL` there is just the age, not the ttl minus the age, as it should be. It's just a bug in the status report, the behavior of the cache is correct.

**Comment by alwendt** [comment]
ok thanks.

**Comment by alwendt** [comment]
Yeah, i tried a newer version but we dont have node 16 on prod

**Comment by isaacs** [comment]
I think latest and greatest works on node 14.latest, as long as you don't rely on fetch having a fully compliant abort controller. Can just load a poly fill or suppress the warning tho, and if you don't use fetch, it's all good.

**Comment by isaacs** [comment]
Ah, yes, I had the `start` and `now` values swapped in the `remainingTTL` calculation 🤦

Fixed on latest release 9.1.1
