### ISSUE TITLE
Incorrect return type for fetch ?

### ISSUE THREAD

**Issue by benasher44** [isaacs/node-lru-cache#295]
The return type shows as `Promise<void | V>`, but I would expect it to match `get` and be `Promise<V | undefined>`

**Comment by isaacs** [comment]
I can see how you get there, but `fetch()` is actually a bit different from `get()`.  Fetch is "go find the value, add it to the cache, and return what you got".  Whereas `get` is simply "tell me what's in the cache at this key (and do the associated recently used dancing if there's something there).

So fetch should really _always_ return a value, except in the case where it gets aborted due to the pending cache entry being evicted or deleted prior to the fetch returning.  By default, such an aborted fetch will simply reject the promise, but with `ignoreFetchAbort` and `allowStaleOnFetchAbort`, you can suppress that failure, but still not have a value to return.

The correct thing to do in that case is to have the `fetchMethod` return _nothing_, not even `undefined`.

It is a bit of an edge case, I'll admit, but full type safety demands that it be called out as a possibility.
