### ISSUE TITLE
How to understand ”when set ttlAutopurge=true, that  may significantly degrade performance“

### ISSUE THREAD

**Issue by scarcoco** [isaacs/node-lru-cache#297]
if i set `ttlAutopurge = true` with `max` parameter( such as `max = 1000`)，that  may significantly degrade performance, too ?

if i want to cleanup stale items, how should i set params? 

At present, the way i think of is either to set the `ttlAutopurge = true` with max parameter, or to clean it regularly, such as 
```
setInterval(() => cache.purgeStale(), 10 * 1000);
```

**Comment by isaacs** [comment]
Perhaps it's helpful to keep in mind that LRUCache is often used in rather performance-intensive situations, and it is designed to perform well even when being slammed thousands or millions of times in a hot path.

If you're using it to cache a slow response from an API server, and really just need to stay below a 50ms response time for 90% of requests, adding a few ms here and there is probably not a big deal. But if you're hitting the cache in a synchronous loop to add a million items, then the overhead of scheduling a million timeouts will definitely be noticeable.

I have been meaning to apply the same optimization to ttlAutopurge that [ttlcache got recently](https://github.com/isaacs/ttlcache/commit/11d7beaf0d32e1c017ccde07df87ed627f612c8b), so there's only ever one timer, but I haven't gotten around to it, and it's not something that anyone has complained about as yet.

**Comment by isaacs** [comment]
Ah, so, to answer your question: if you only want to purge stale items once per 10 seconds, rather than set an interval, it might be just a bit more efficient to do `{ ttlAutopurge: true, ttlResolution: 10_000 }`.

That has slightly different semantics, since basically it would mean that any time within 10s would be _the same time_, because it'll only check the clock that often, and you'll return stale items for 10 seconds.

If you just want to automatically purge old items, I'd probably just try it with `ttlAutopurge:true`, and if it's not enough of a perf hit for you to notice, then leave it.  It almost certainly is still going to be way faster than whatever you're caching, if you're bothering to use a cache in the first place.
