### ISSUE TITLE
dispose/disposeAfter aren't called on replace

### ISSUE THREAD

**Issue by orgads** [isaacs/node-lru-cache#309]
```javascript
import { LRUCache } from 'lru-cache';
import { setTimeout } from 'timers/promises';

const clientCache = new LRUCache({
  ttl: 50,
  max: 3,
  fetchMethod: () => Promise.resolve('value'),
  dispose: (value) => console.log(`Disposing ${value}`),
});

await clientCache.fetch('foo');
await setTimeout(60);
await clientCache.fetch('foo');
```

I'd expect `dispose` to be called on the second fetch, but it isn't.

**Comment by isaacs** [comment]
Good bug, clear repro, thanks!

The issue is that it did not call `dispose()` when replacing a fetch-in-progress indicator, because of course, if the fetch is for the value being set, then you don't need to "dispose" of that. And we don't call dispose() when _creating_ that fetch-in-progress indicator, because the entry hasn't actually been replaced yet.

The missing piece was, when replacing a fetch-in-progress, we need to call dispose() on its stored `__staleWhileFetching` value, because at that point, it _is_ being replaced.
