### ISSUE TITLE
Unexpected token '('

### ISSUE THREAD

**Issue by accap3035** [isaacs/node-lru-cache#314]
I want to use mysql2 library in nodejs but whenever I try to run application i throws error like this I could't find any unexpected item in the index-cjs.js file

xxxxx/node_modules/mysql2/node_modules/lru-cache/dist/cjs/index.js:359
    #initializeTTLTracking() {
                          ^

SyntaxError: Unexpected token '('
at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (xxxxx/node_modules/mysql2/node_modules/lru-cache/dist/cjs/index-cjs.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by isaacs** [comment]
You need a JavaScript platform that understands private class members. That's why there's an `engines` field in package.json.

**Comment by marcoantoniogarcialeon77** [comment]
@isaacs I'm having the same issue, this is my package.json, could you help me to understand what's happening?. Thanks in advance.

{
    "name": "NAME",
    "version": "1.0.0",
    "description": "name",
    "main": "app.js",
    "scripts": {
        "web": "set NODE_ENV=web&& npx nodemon src/app.js",
        "dev": "set NODE_ENV=development&& npx nodemon src/app.js",
        "qa": "set NODE_ENV=qa&& npx nodemon src/app.js",
        "prod": "set NODE_ENV=production&& npx nodemon src/app.js",
        "start": "set NODE_ENV=production&& npx nodemon src/app.js",
        "sass": "node-sass -w src/scss/ -o public/css/ --recursive"
    },
    "keywords": [],
    "author": "My NAme",
    "license": "ISC",
    "dependencies": {
        "axios": "^0.24.0",
        "body-parser": "^1.19.0",
        "bootstrap": "^5.2.3",
        "bootstrap-icons": "^1.10.5",
        "cookie-parser": "^1.4.5",
        "cors": "^2.8.5",
        "datatables.net": "^1.13.1",
        "datatables.net-dt": "^1.13.1",
        "dotenv": "^10.0.0",
        "ejs": "^3.1.6",
        "express": "^4.18.2",
        "express-session": "^1.17.3",
        "file-saver": "^2.0.5",
        "jquery": "^3.6.4",
        "jsonwebtoken": "^9.0.0",
        "morgan": "^1.10.0",
        "msnodesqlv8": "^2.4.0",
        "multer": "^1.4.3",
        "mysql2": "^3.6.0",
        "node-csv": "^0.1.2",
        "node-excel-export": "^1.4.4",
        "node-vault": "^0.10.2",
        "request": "^2.88.2"
    },
    "devDependencies": {
        "nodemon": "^2.0.13"
    }
}

What is missing?

**Comment by isaacs** [comment]
Put this line in your program somewhere:

```
console.log(process.version)
```

Run it in the environment where the error occurs. Inspect the output. 

Observe that it is not within the stated engines range for this library.

**Comment by brunoar86** [comment]
Solução:

npm uninstall mysql2
npm install mysql2@3.0.0

**Comment by runt1me** [comment]
I'm at node version 16.20.2, mysql2 version 3.6 breaks this for me as well. Downgrading to mysql2 version 3.0.0 fixes the problem as stated above since it also lowers the version of lru-cache to before the breaking change, but I can't figure out why.

From node_modules/lru-cache/package.json:
```
"engines": {
    "node": ">=16.14"
  },
```

I'm fine downgrading to mysql2 v3.0.0, as it has no special impact on my particular project, but I am still curious why this is not compatible with node 16.20.2.

**Comment by isaacs** [comment]
Yup. There are few certainties in software development, but if you get a syntax error, then you can guarantee it's running on a VM that doesn't understand how to interpret the syntax in question, every time. That's literally the only way to cause that error. If you think it's running on a VM that does interpret that syntax, then check all the assumptions, because one of them is incorrect, 100% guaranteed. Either it's not running what you think it is, or not running on the version you think it is, etc.

**Comment by Post1X** [comment]
Thanks alot. Downgrading mysql2 to 3.0.0 helped me too

**Comment by sandeepsinghrules** [comment]
Downgrading mysql2 to 3.0.0 helped me too
