### ISSUE TITLE
fetch: truthy promise resolution typing

### ISSUE THREAD

**Issue by mfulton26** [isaacs/node-lru-cache#329]
The return type for `fetch` in each of the current two overloads is `Promise<undefined | V>`.

However, `fetch` should always resolve to `V` except when certain options are set (e.g. `ignoreFetchAbort` and `allowStaleOnFetchAbort`).

As the return type is now, callers must resort to solutions like `!` to tell TypeScript type checking that the value won't be `undefined`:

```ts
const value: V | undefined = await cache.fetch(key);
```

```ts
const value: V = (await cache.fetch(key))!;
```

Is it possible to add additional overrides for `fetch` to define return a return type of `Promise<V>` for whenever the `LRUCache` instance wasn't constructed with options that would allow resolving to `undefined`? If that is too complicated or otherwise isn't feasible at this time, then what about adding an alternative method that always fetches or throws independent of those options which never resolves to `undefined` (e.g. `fetchOrError`)?

```ts
const value: V = await cache.fetch(key);
```

or

```ts
const value: V = await cache.fetchOrError(key);
```

**Comment by isaacs** [comment]
I think I explored this a while back and the combinatorial explosion of typescript calculus was just too much even for me. (And I'm guilty of writing some truly [brutal type calculus](https://github.com/tapjs/tapjs/blob/main/src/intercept/src/index.ts) so that's really saying something.)

I just took a quick pass at what it might imply, and since `ignoreFetchAbort` can be provided either to the constructor or the `fetch()` method directly, it's quite complicated.

So, the way forward here is with a `cache.forceFetch(k)` method, which will reject if `cache.fetch()` resolves to `undefined`.
