### ISSUE TITLE
Published package contains unusable source condition

### ISSUE THREAD

**Issue by guybedford** [isaacs/node-lru-cache#339]
I've been using the `"source"` condition locally for testing my application against unoptimized sources, but when enabled this condition causes lru-cache to break due to the `"source"` condition being present here.

I guess we are kinda using it the same way, and perhaps that way should require stripping this field on publish, but the workflows don't really exist to do that.

Would you be open to publishing a version without the `"source"` condition in use? Finding myself wanting to rename my source condition to `"original"` and then using that, but realising this is a losing game without coordination!

**Comment by isaacs** [comment]
Yeah, it's especially weird if the source isn't available. I'll have to change this behavior in tshy, I think. For the short term though, would it be ok to use if the source _is_ available in the package?

**Comment by guybedford** [comment]
I was happy to work with `"source"` existing here, tried setting up my Node.js test process to use a ts-node so that it would still run. As long as it can run with `"source"` present under that kind of standard expectation, it seems fine to me.

But yeah, in terms of ideal workflows, perhaps the expected workflow of a `"source"` field is to strip it.

**Comment by isaacs** [comment]
So, one downside I can see with "source that refers to ts version of an export, which is present" is that it's no longer hybrid if you load it with a ts-node or similar; it'd _only_ be ESM. So, really, it should only be available down the `import` path.

For source resolution internally, tshy now supports defining a `sourceDialects` list, so you can make it project-specific. Maybe instead of creating a plain `source` condition by default, tshy could create a `${name}/source` condition by default. Then you could decide on a package-by-package basis which ones you wanted to reference by source vs build.

It could also force the `files` field to include `['dist', 'src']`, to ensure that source is present if exported.

**Comment by guybedford** [comment]
In general, I got the feeling that working with unbuilt sources would make sense for local package development and workspace development, but any time that package is published, you never want to reference the original sources after that, so that the `"source"` condition is only ever a local package development phenomenon (ie present for the GitHub repo, but not on npm).

But I'm not completely up to speed on how tshy uses the `"source"` field here, and if it is like the above style of workflows or not.

**Comment by isaacs** [comment]
Yeah, where I'm kind of landing with this is that any source that tshy adds to exports unconditionally (ie, not explicitly opt-in), needs to be package-name-specific. I think that'll fix it for your use case, but I am also going to investigate if maybe I can ship the source in a nice portable way. I'm hearing interesting things about `isolatedDeclarations`, which supposedly makes transpiling and type generation a lot faster.

**Comment by isaacs** [comment]
But for example, I wouldn't need to use `inlineSources` in the source map files, because the source would just be there to reference by path.

**Comment by isaacs** [comment]
Decided to just remove the `source` export, and see how that goes. `sourceDialects` is a better solution for its use cases anyway.
