### ISSUE TITLE
MRU & Max Safe Integer

### ISSUE THREAD

**Issue by johngeorgewright** [isaacs/node-lru-cache#50]
I can see a potential flaw in your [`_mru`](/isaacs/node-lru-cache/blob/master/lib/lru-cache.js#L167) counter. We're using lru-cache as our services receive several thousand requests a second. If there is never any reduction in the MRU counter, eventually it'll overflow the `Number.MAX_SAFE_INTEGER` and things will begin to go pair shaped.

To create ourselves a safety net, we have implemented an interval that resets the cache every hour. Would you consider a configurable option to do something like this in your module? Or maybe just something that resets when it sees the MRU is at the `MAX_SAFE_INTEGER`?

**Comment by johngeorgewright** [comment]
It also looks like the `_lru` counter is doing the same thing.

**Comment by isaacs** [comment]
This took a lot of refactoring to get past, but it's fixed in 3.1.1.

Thanks for pointing it out!  I'm pretty sure it was also the source of a really weird case I'd had trouble nailing down once upon a time.  See the commit message in f95bf1f72744c7dc323f27b35331512aebdfa9ca for details if you're curious.
